### PR TITLE
Added adobe reader dc

### PR DESCRIPTION
**Pull request by pahofmann**

### CODE REVIEW

**Comment by Fmstrat** [comment]
Thanks for contributing! Looks like there are some conflicts that need resolution, though. Once those are cleaned up I can merge.

**Comment by Fmstrat** [comment]
Thanks, getting close now. A few items:
- Looks like things got out of alpha order in the `README` (Photoshop, Premiere, for example)
- Can you name in the README "Adobe Acrobat Reader Pro" (full name for alpha sort)
- Lastly, is there a 64bit version, or is Reader always in x86 folder?

**Comment by pahofmann** [comment]
Changed the name and fixed alpha order.  I haven't found a 64bit version of the reader.

**Comment by Fmstrat** [comment]
This is now in `main`, but with it renamed from Adobe Acrobat Reader Pro to Adobe Acrobat Reader (DC), and a minor fix on the HTML table. Thanks!

**Pull request merged**
