### PR TITLE
Enable audio redirect FreeRDP

### PR DESCRIPTION
**Pull request by Pipodi**
This feature enables audio redirect on FreeRDP for every app, even manual launches. I tried it with Amazon Music and works. 

Edited the README a bit to guide the user to add the right permissions and audio device passthrough.

### CODE REVIEW

**Comment by Pipodi** [comment]
Didn't see that there was an "RDP flags" option in winapps.conf, so I removed the hardcoded flag and rewrited the section for the audio passthrough via PA.

**Comment by Fmstrat** [comment]
Out of curiosity, is there a reason we wouldn't want to do this by default?

**Comment by Pipodi** [comment]
What do you mean "by default"? Is `/audio-mode:1` flag enable by default? Or am I missing something?

**Comment by Fuseteam** [comment]
i don't think there's a reason we wouldn't want this by default :thinking:

**Pull request closed without merging**
