### PR TITLE
feat: redirect clipboard with xfreerdp

### PR DESCRIPTION
**Pull request by devksingh4**
Clipboard redirection can be useful when working in Word, etc. Using the +clipboard option in xfreerdp enables this

### CODE REVIEW

**Comment by Fmstrat** [comment]
What version of FreeRDP are you running? Clipboard redirection is on my default in the latest version.

**Comment by devksingh4** [comment]
2.2.0 on Ubuntu 20.04 LTS

It is not on by default for me.

**Comment by Fmstrat** [comment]
Really? With 2.2.0 in 20.04 I see:
```bash
$ man xfreerdp |grep clipboard
       -clipboard
           Redirect clipboard (default:on)
       +clipboard
           Activate clipboard redirection
```
Is your default not on? I ask because I have the same setup and can cut/paste fine between the environments.

**Comment by devksingh4** [comment]
Mine does not have default on, and copying between the two doesn't work. This might also be useful for 18.04 and 16.04 anyways.

**Comment by Tiebe** [comment]
It can't hurt to add the option anyways

**Comment by Fmstrat** [comment]
Good point, I've repointed this at the `develop` branch and it appears there are some conflicts. If those can be resolved I'll merge. Thanks!

**Comment by devksingh4** [comment]
@Fmstrat should be good now.

**Pull request merged**
