### PR TITLE
Add Visual Studio 2019

### PR DESCRIPTION
**Pull request by lawrencegripper**
Thanks for much for putting this repo together, having a play today and really enjoying it. 

Here is a PR adding Visual Studio 2019 to the apps.

### CODE REVIEW

**Comment by lawrencegripper** [comment]
Just spotted the repo doesn't have a license (#17), would it be ok to add MIT or similar to this PR?

**Comment by Fmstrat** [comment]
Nice! Could you add some base mime types? Such as for text files?

**Comment by lawrencegripper** [comment]
Sure, no problem. I've updated this now. Looks like this isn't as nice as it could be but have added what we can, ref: https://askubuntu.com/questions/1240366/how-to-set-default-application-based-on-file-extension-not-mime-type

**Comment by MrSquigy** [comment]
This is for the enterprise version of VS2019 FYI, would need to change 
`WIN_EXECUTABLE="C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\devenv.exe"` 
to 
`WIN_EXECUTABLE="C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\devenv.exe"` 
for the community edition

**Comment by lawrencegripper** [comment]
> This is for the enterprise version of VS2019

Good shout, I've created `vs2019community` and renamed this one to `vs2019enterprise`.

**Comment by kcalvelli** [comment]
Would it be possible to add Professional as well, please?

WIN_EXECUTABLE="C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\devenv.exe"

**Comment by lawrencegripper** [comment]
@kcalvelli Sure - done. 

@Fmstrat No problem, I've rebased onto main, updated the readme and added a reference to Wikipedia for where I got the Icon (https://en.wikipedia.org/wiki/File:Visual_Studio_Icon_2019.svg)

**Review by yezz123 — COMMENTED** [review]
But the running file for the debug or build pack can't be using on linux they are build as .dll file and also windows running soo just one think is the virtual debug or build and i guess this can work !

**Comment by lawrencegripper** [comment]
@Fmstrat Rebased onto the new changes in main, good to go I think.

**Comment by Fmstrat** [comment]
@lawrencegripper  So close! Hah. Is there a license for the icon? If not, here is the Libre icon that we already have the license displayed for in the README:
```
<svg role="img" focusable="false" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 14 14"><path d="m 7.6993595,3.353836 c -1.296839,1.296838 -2.3877961,2.353305 -2.4392664,2.353305 -0.04298,0 -0.7556047,-0.523723 -1.5717002,-1.159407 L 2.2111433,3.388326 1.0087555,3.98952 l 0,6.01247 1.2023878,0.601194 1.3658191,-1.064957 C 4.3330978,8.945523 5.0287422,8.41331 5.1231928,8.352819 5.2951141,8.249878 5.4665048,8.404289 7.6913995,10.620694 L 10.070706,13 l 1.46027,-0.592704 1.460268,-0.584214 0,-9.654654 -1.116427,-0.446783 C 11.265135,1.472253 10.60345,1.214902 10.406059,1.137431 L 10.053726,1 7.7004205,3.353305 Z M 10.027195,6.99602 c 0,1.322839 -0.01698,2.404776 -0.051471,2.404776 -0.120451,0 -3.04046,-2.353305 -3.01499,-2.430776 0.026,-0.09445 2.903029,-2.370816 3.0065,-2.370816 0.034489,-0.0085 0.060489,1.073447 0.060489,2.396286 z M 3.1986295,6.136945 4.0577053,6.99602 3.1986295,7.855096 c -0.472253,0.472253 -0.8845457,0.859076 -0.9190361,0.859076 -0.04298,0 -0.068981,-0.773115 -0.068981,-1.717621 0,-0.944506 0.02547,-1.718152 0.068981,-1.718152 0.03449,0 0.4467831,0.386823 0.9190361,0.859076 z" fill="#000000"/></svg>
```
Just change the `fill` to a purple from the existing icon (`gpick` is helpful here). Thanks!

**Comment by Fmstrat** [comment]
Actually, I'll just merge this in and handle the icon. ;)

**Pull request merged**
